In [1]:
!pip install numpy as np

  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13655 sha256=bc3ec0322b76eba2733f578d8d1079f2ac5bf48ad76b906744c34cd546650b09
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\44\c8\fa\6341ec15fc1b7f1d7813744425e23817719133e2e6d2da01c9
Successfully built np


In [11]:
import numpy as np

In [12]:
some_list = [1,2,3,4,5,6]
type(some_list)

list

In [13]:
some_list = np.array(some_list)
type(some_list)

numpy.ndarray

In [14]:
some_list

array([1, 2, 3, 4, 5, 6])

In [16]:
ones_array = np.ones(5)

ones_array

array([1., 1., 1., 1., 1.])

In [18]:
range_array = np.arange(8)

range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
#Reshaped_array reshaped the array into specific dimension like Here it is 2*4
reshaped_array1 = range_array.reshape(2,4)
reshaped_array1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
reshaped_array2 = range_array.reshape(4,2)
reshaped_array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [29]:
# Here we will get a random array of particular dimension
random_array = np.random.random((2,4))
random_array

array([[0.63460983, 0.96316694, 0.98417173, 0.94344044],
       [0.23399975, 0.28184277, 0.08283803, 0.95760071]])

In [33]:
mean = np.mean(random_array)
print("Mean of the random array {} is: {}".format(random_array,mean))

Mean of the random array [[0.63460983 0.96316694 0.98417173 0.94344044]
 [0.23399975 0.28184277 0.08283803 0.95760071]] is: 0.6352087761818407


In [35]:
median = np.median(random_array)
print(median)

0.7890251349989945


In [36]:
standar_deviation = np.std(random_array)
print(standar_deviation)

0.3569357514710452


In [40]:
a,b = mean - 3*standar_deviation , mean + 3*standar_deviation
print(a,b)

-0.43559847823129505 1.7060160305949763
